一个请求发送出去之后，我们可以对HTTP的状态码做出断言，在TP单元测试扩展中对状态码做出响应主要有两个方法：
1. assertResponseOk：无参数，单元状态码为200
2. assertResponseStatus：接受一个状态码作为参数，并对这个状态码直接断言

#  assertResponseOk
在快速入门的编写一个简单的测试用例中，我们只有两个测试类，一个是我们编写的，一个是安装扩展的时候自带的。只有两个测试类并且各自只有一个测试方法，理论上只有两个断言，但是却有两个测试类，四个断言。这是因为在单元测试扩展中，当我们构建一个请求的时候，扩展会使用本方法进行断言。

# assertResponseStatus
接受一个参数，该参数是要断言的状态码。
assertResponseOk内部便是使用该方法进行断言的。


# 例子
注意如果要使用redirect的话，就需要让控制器继承think\Controller。
~~~
<?php
namespace app\index\controller;
use think\Controller;
class Index extends Controller
{
	public function index(){
		return 'test';
	}
	
	public function index2(){
		$this->redirect('http://www.baidu.com',302);
	}
}
~~~
针对上面的控制器进行测试：
~~~
<?php
namespace tests;
//针对Index控制器
class IndexTest extends TestCase
{
	public function testOutput(){
		$this->visit('/index/index/index')->assertResponseOk();
	}
	public function testNo(){
		$this->visit('/index/index/index2')->assertResponseStatus(200);
	}
}
~~~
>注意，这里的testNo应该是断言200的。在TP扩展中，assertResponseStatus目前阶段基本没有什么用处。因为当发生302的时候，扩展框架会重新就转移地址重新发起一个请求。因此上文中的转移到百度的页面，实际上还是会被重新转发到TP的App::run中，因此返回的结果会是test。例子如下:

~~~
public function testNo(){
		$response=$this->visit('/index/index/index2');
		$response->assertResponseStatus(200);//不是302
		$response->see('test');//OK
}
~~~

# 对异常断言

当程序使用AOP来实现权限认证的时候，有可能当用户没有登录的时候，会返回401错误。但是在TP测试框架中，非200的状态码都会抛出一个异常，因此我们可以通过断言异常来判断权限认证：

```
	/**
     * @expectedException think\testing\HttpException
     */
    public function testDeleteUser_noLogin(){
        $this->visit('/admin/test/test');//由于用户没有登录，会返回401，而TP测试框架会抛出异常
    }
```